{{- if and .Values.mastodon.smtp.bulk.enabled (not .Values.mastodon.smtp.bulk.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-smtp-bulk" (include "mastodon.fullname" .) }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.mastodon.smtp.bulk.login }}
  login: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.mastodon.smtp.bulk.password }}
  password: {{ . | b64enc }}
  {{- end }}
{{- end }}
